plugins {
	id 'com.android.application' version '9.2.0' apply false
}

apply plugin: 'com.android.application'

android {
	namespace = "com.android.inputmethod.latin"

	// Required if using classes in android.test.runner
	useLibrary 'android.test.runner'

	// Required if using classes in android.test.base
	useLibrary 'android.test.base'

	// Required if using classes in android.test.mock
	useLibrary 'android.test.mock'

	compileSdk = 36

	defaultConfig {
		minSdk = 21
		targetSdk = 37
		versionCode = 7
		versionName = "0.7"
		
		testApplicationId 'com.android.inputmethod.latin.tests'
		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		vectorDrawables.useSupportLibrary = false
		
		ndk {
			abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
		}
	}
	
	externalNativeBuild {
		cmake {
			path "native/jni/CMakeLists.txt"
		}
	}
	
	ndkVersion = "28.2.13676358"
	
	buildTypes {
		debug {
			debuggable = true
			minifyEnabled = false
			zipAlignEnabled = false
			shrinkResources = false
		}
		release {
			debuggable = false
			minifyEnabled = false
			zipAlignEnabled = true
			shrinkResources = false
			proguardFiles (
				getDefaultProguardFile("proguard-android-optimize.txt"),
				"java/proguard.flags"
			)
		}
	}
	
	sourceSets {
		main {
			res.srcDirs = ['java/res']
			java.srcDirs = ['common/src', 'java/src']
			manifest.srcFile 'java/AndroidManifest.xml'
		}

		androidTest {
			res.srcDirs = ['tests/res']
			java.srcDirs = ['tests/src']
			manifest.srcFile "tests/AndroidManifest.xml"
		}
	}
	
	androidResources {
		noCompress 'dict'
	}
	
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
	implementation 'com.google.code.findbugs:jsr305:3.0.2'
	implementation 'androidx.viewpager2:viewpager2:1.1.0'
	implementation 'com.google.android.material:material:1.13.0'
	implementation 'androidx.preference:preference:1.2.1'

	testImplementation 'junit:junit:4.12'
	androidTestImplementation "org.mockito:mockito-core:1.9.5"
	androidTestImplementation 'com.google.dexmaker:dexmaker:1.2'
	androidTestImplementation 'com.google.dexmaker:dexmaker-mockito:1.2'
	androidTestImplementation 'androidx.test.ext:junit:1.1.1'
	androidTestImplementation 'androidx.test:rules:1.1.1'
	androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'
	androidTestImplementation 'androidx.annotation:annotation:1.0.0'
}
