plugins {
	id 'com.android.application' version '9.2.0' apply false
}

apply plugin: 'com.android.application'

android {
	namespace = "com.android.inputmethod.latin"
	
	compileSdk = 37
	
	defaultConfig {
		minSdk = 21
		targetSdk = 37
		versionCode = 1
		versionName = "0.1"
		
		applicationId = "com.amanoteam.flonne"
		
		vectorDrawables.useSupportLibrary = false
		
		ndk {
			abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
		}
	}
	
	externalNativeBuild {
		cmake {
			path "native/jni/CMakeLists.txt"
		}
	}
	
	ndkVersion = "28.2.13676358"
	
	buildTypes {
		debug {
			debuggable = true
			minifyEnabled = false
			zipAlignEnabled = false
			shrinkResources = false
		}
		release {
			debuggable = false
			minifyEnabled = false
			zipAlignEnabled = true
			shrinkResources = false
			proguardFiles (
				getDefaultProguardFile("proguard-android-optimize.txt"),
				"java/proguard.flags"
			)
		}
	}
	
	sourceSets {
		main {
			res.srcDirs = ['java/res']
			java.srcDirs = ['common/src', 'java/src']
			manifest.srcFile 'java/AndroidManifest.xml'
		}
	}
	
	androidResources {
		noCompress 'dict'
	}
	
    lint {
        abortOnError = false
        checkReleaseBuilds = false
    }
}

dependencies {
	implementation 'com.google.code.findbugs:jsr305:3.0.2'
	implementation 'androidx.viewpager2:viewpager2:1.1.0'
	implementation 'com.google.android.material:material:1.13.0'
	implementation 'androidx.preference:preference:1.2.1'
}
